[log]
level = "libaster=info" # "trace" "info" "debug" "warn" "error"
ansi = true  # support ANSI colors
stdout = false # print logs to stdout
directory = "/var/log/rcproxy" # log file directory
file_name = "rcproxy.log" # log file name

[metrics]
port = 2110

[[clusters]]
name = "test-cluster"
listen_addr = "0.0.0.0:7788"
hash_tag = "{}"
thread = 1
cache_type = "redis_cluster"
servers = ["127.0.0.1:7000", "127.0.0.1:7001", "127.0.0.1:7002", "127.0.0.1:7003", "127.0.0.1:7004", "127.0.0.1:7005"]

fetch_interval = 1800000 # 1800s , 30 minutes
fetch_since_latest_cmd = 1000 # 3600s , 1 hour
read_from_slave = false

ping_fail_limit = 10
ping_interval = 300

read_timeout = 1000
write_timeout = 1000
dial_timeout = 500
listen_proto = "tcp"
node_connections = 1

auth = "" # mypassw
